version: '3'

services:
  blog-database:
    image: postgres:14
    container_name: blog-database
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blog-db
    expose:
      - "5232"
    ports:
      - "5232:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#      - ./init-local-db:/docker-entrypoint-initdb.d