spring:
  datasource:
    url: jdbc:postgresql://localhost:5232/blog-db
    username: "blog"
    password: "blog"
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 10
        order_inserts: true
        format_sql: true
        generate_statistics: true
  liquibase:
    enabled: false